#line 2 "Lexer.c"
#line 4 "rholang_mercury.l"
/* strdup was not in the ISO C standard before 6/2019 (C2x), but in POSIX 1003.1.
 * See: https://en.cppreference.com/w/c/experimental/dynamic/strdup
 * Setting _POSIX_C_SOURCE to 200809L activates strdup in string.h.
 */
#define _POSIX_C_SOURCE 200809L



#line 12 "Lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer rholang_mercury__create_buffer
#define yy_delete_buffer rholang_mercury__delete_buffer
#define yy_flex_debug rholang_mercury__flex_debug
#define yy_init_buffer rholang_mercury__init_buffer
#define yy_flush_buffer rholang_mercury__flush_buffer
#define yy_load_buffer_state rholang_mercury__load_buffer_state
#define yy_switch_to_buffer rholang_mercury__switch_to_buffer
#define yyin rholang_mercury_in
#define yyleng rholang_mercury_leng
#define yylex rholang_mercury_lex
#define yylineno rholang_mercury_lineno
#define yyout rholang_mercury_out
#define yyrestart rholang_mercury_restart
#define yytext rholang_mercury_text
#define yywrap rholang_mercury_wrap
#define yyalloc rholang_mercury_alloc
#define yyrealloc rholang_mercury_realloc
#define yyfree rholang_mercury_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE rholang_mercury_restart(rholang_mercury_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t rholang_mercury_leng;

extern FILE *rholang_mercury_in, *rholang_mercury_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up rholang_mercury_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up rholang_mercury_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via rholang_mercury_restart()), so that the user can continue scanning by
	 * just pointing rholang_mercury_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when rholang_mercury_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t rholang_mercury_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow rholang_mercury_wrap()'s to do buffer switches
 * instead of setting up a fresh rholang_mercury_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void rholang_mercury_restart (FILE *input_file  );
void rholang_mercury__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE rholang_mercury__create_buffer (FILE *file,int size  );
void rholang_mercury__delete_buffer (YY_BUFFER_STATE b  );
void rholang_mercury__flush_buffer (YY_BUFFER_STATE b  );
void rholang_mercury_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void rholang_mercury_pop_buffer_state (void );

static void rholang_mercury_ensure_buffer_stack (void );
static void rholang_mercury__load_buffer_state (void );
static void rholang_mercury__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER rholang_mercury__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE rholang_mercury__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE rholang_mercury__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE rholang_mercury__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *rholang_mercury_alloc (yy_size_t  );
void *rholang_mercury_realloc (void *,yy_size_t  );
void rholang_mercury_free (void *  );

#define yy_new_buffer rholang_mercury__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        rholang_mercury_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            rholang_mercury__create_buffer(rholang_mercury_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        rholang_mercury_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            rholang_mercury__create_buffer(rholang_mercury_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define rholang_mercury_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *rholang_mercury_in = (FILE *) 0, *rholang_mercury_out = (FILE *) 0;

typedef int yy_state_type;

extern int rholang_mercury_lineno;

int rholang_mercury_lineno = 1;

extern char *rholang_mercury_text;
#define yytext_ptr rholang_mercury_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up rholang_mercury_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	rholang_mercury_leng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[173] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   76,   75,   74,   73,
       73,   33,   74,   12,   72,    8,    9,    6,   14,   25,
       10,    7,   11,   69,   38,   31,   17,   23,   19,   27,
       72,   72,   72,   72,   72,   36,   74,   37,   26,   74,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,    1,   24,    2,    3,   67,   68,   67,   34,   22,
        0,   70,    0,   13,   72,   72,   15,   39,   16,    0,
       65,   64,    4,   69,   30,    0,   18,   21,   35,   20,
       72,   72,   72,   72,   72,   72,   72,    5,   72,   72,

        0,    0,   71,   72,   72,   72,   72,   72,   72,   55,
       56,   72,   72,   72,   61,   72,   72,   66,   40,   64,
       32,   72,   72,   43,   44,   45,   72,   47,   48,   72,
       72,   72,   72,   54,   72,   59,   60,   72,   72,   41,
       72,   72,   72,   72,   52,   72,   72,   72,   63,   72,
       72,   72,   72,   53,   57,   72,   72,   46,   49,   72,
       72,   62,   72,   28,   29,   50,   72,   58,   72,   51,
       42,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,   23,   24,   25,   26,   26,   26,   26,
       26,   26,   27,   26,   26,   26,   26,   28,   26,   26,
       26,   26,   29,   26,   30,   26,   26,   26,   26,   26,
       31,   32,   33,    1,   34,   35,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   26,   26,   45,   46,   47,
       48,   26,   26,   49,   50,   51,   52,   26,   53,   26,
       54,   26,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[180] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   56,   57,  225,  420,  420,  420,
      420,   57,   57,  217,   56,  420,  420,  420,  210,  209,
      203,  199,   54,   54,  420,  420,   52,   53,  146,  420,
       61,   69,   70,   72,   73,  420,  151,  420,   74,   50,
       77,   76,   84,   85,   91,   95,  110,   86,  106,  114,
      124,  420,  420,  420,  420,  420,  420,  146,  420,  420,
      128,  420,  130,  420,  130,  131,  420,  420,  420,  136,
      420,    0,  420,   71,  420,   92,  420,  420,  420,  420,
      134,  136,  138,  140,  142,  145,  144,  420,  146,  149,

       62,   64,  420,  152,  150,  156,  162,  164,  168,  185,
      188,  192,  193,  194,  197,  199,  198,  420,  420,    0,
      420,  203,  200,  201,  204,  207,  208,  213,  217,  222,
      223,  229,  232,  242,  246,  247,  251,  252,  253,  255,
      264,  257,  260,  261,  263,  266,  265,  283,  268,  289,
      294,  300,  296,  305,  307,  308,  309,  311,  337,  317,
      312,  315,  318,  420,  420,  322,  326,  330,  350,  354,
      356,  420,  404,  407,  410,   98,   97,  413,  416
    } ;

static yyconst flex_int16_t yy_def[180] =
    {   0,
      173,  173,  172,    3,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  174,  174,  172,  172,  172,  172,
      172,  172,  175,  172,  176,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      176,  176,  176,  176,  176,  172,  172,  172,  177,  178,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      175,  172,  172,  172,  176,  176,  172,  172,  172,  172,
      172,  179,  172,  172,  172,  172,  172,  172,  172,  172,
      176,  176,  176,  176,  176,  176,  176,  172,  177,  177,

      178,  172,  172,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  172,  172,  179,
      172,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  172,  172,  176,  176,  176,  176,  176,
      176,    0,  172,  172,  172,  172,  172,  172,  172
    } ;

static yyconst flex_int16_t yy_nxt[479] =
    {   0,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   34,   35,   36,   37,
       38,   39,   40,   25,   41,   25,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   25,   54,
       55,   25,   25,   56,   25,   57,   58,   59,   25,   60,
       61,   25,   25,   25,   62,   63,   64,   65,   67,   67,
       69,   72,   75,   81,   85,   68,   68,   75,   82,   84,
       84,   86,   87,   88,   89,   75,   75,   70,   75,   75,
       99,  102,   75,   75,  103,   83,   84,   84,   73,   75,
       75,   75,   75,  102,   75,  101,  103,   75,  101,  100,

       76,   75,   75,   75,  121,   75,   75,   99,   91,   75,
       75,   95,   75,   94,   92,   93,   75,   75,   75,   75,
       75,   97,   96,  104,   75,  113,  108,  105,   75,  107,
       75,  106,   72,  114,   71,  110,   75,   75,  109,   75,
       75,  111,   75,   75,   75,  112,   75,   75,   75,  119,
       75,   75,   99,  116,  115,   99,   75,   75,   75,   73,
      118,   71,   75,   75,   75,   98,   90,   75,   75,   75,
       75,   75,  117,   75,   75,   75,   71,   75,   75,   99,
       71,  122,   99,   75,  125,   75,  123,  128,  124,   75,
      129,   75,  126,  127,   75,   75,  130,   75,   75,   75,

       75,   75,  131,   75,   75,   75,   75,   75,  133,   75,
       75,  132,   80,   75,   75,   79,  134,   78,   75,   75,
       77,   75,   74,   75,  172,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,  141,
       75,   75,  135,  138,  137,  136,   75,  140,   75,  139,
       75,  142,   75,   75,  172,   75,   75,   75,   75,   75,
      143,   75,   75,   75,  172,   75,   75,   75,  145,   75,
       75,   75,   75,  144,   75,   75,  172,  172,  172,   75,
       75,  146,  172,  147,   75,   75,   75,  150,   75,   75,
       75,  148,  149,   75,   75,   75,   75,   75,   75,   75,

       75,   75,   75,  151,  152,  154,   75,  155,  172,  153,
      172,   75,  172,   75,   75,   75,   75,   75,   75,  172,
      156,   75,   75,   75,   75,  172,  172,   75,   75,   75,
      172,  160,   75,   75,  172,  158,   75,  157,   75,  159,
       75,   75,   75,   75,   75,   75,  161,  164,   75,  165,
       75,   75,  166,  169,  167,   75,   75,  163,  162,   75,
       75,  168,   75,   75,  172,  172,  172,  172,  172,  172,
       75,  172,  172,  172,  172,  172,  170,  172,  172,  172,
      172,  172,  172,   75,  172,  172,  172,   75,  172,   75,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,

      172,  172,  172,  171,   18,   18,   18,   66,   66,   66,
       71,   71,   71,  101,  101,  101,  120,  172,  120,   17,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172
    } ;

static yyconst flex_int16_t yy_chk[479] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   15,   16,
       22,   23,   25,   33,   37,   15,   16,   41,   33,   34,
       34,   37,   37,   38,   38,   42,   43,   22,   44,   45,
       49,   50,   52,   51,   50,   33,   84,   84,   23,   25,
       53,   54,   58,  101,   41,  102,  101,   55,  102,  177,

      176,   56,   42,   43,   86,   44,   45,   49,   41,   52,
       51,   44,   59,   43,   41,   42,   57,   53,   54,   58,
       60,   45,   44,   51,   55,   58,   55,   52,   56,   54,
       61,   53,   71,   58,   73,   56,   75,   76,   55,   59,
       91,   56,   92,   57,   93,   57,   94,   60,   95,   80,
       97,   96,   99,   60,   59,  100,  105,   61,  104,   71,
       68,   73,  106,   75,   76,   47,   39,   91,  107,   92,
      108,   93,   61,   94,  109,   95,   73,   97,   96,   99,
       73,   91,  100,  105,   94,  104,   92,   97,   93,  106,
      104,  110,   95,   96,  111,  107,  105,  108,  112,  113,

      114,  109,  106,  115,  117,  116,  123,  124,  108,  122,
      125,  107,   32,  126,  127,   31,  109,   30,  110,  128,
       29,  111,   24,  129,   17,  112,  113,  114,  130,  131,
      115,  117,  116,  123,  124,  132,  122,  125,  133,  123,
      126,  127,  112,  116,  114,  113,  128,  122,  134,  117,
      129,  127,  135,  136,    0,  130,  131,  137,  138,  139,
      130,  140,  132,  142,    0,  133,  143,  144,  132,  145,
      141,  147,  146,  131,  149,  134,    0,    0,    0,  135,
      136,  133,    0,  135,  137,  138,  139,  141,  140,  148,
      142,  138,  139,  143,  144,  150,  145,  141,  147,  146,

      151,  149,  153,  142,  143,  146,  152,  147,    0,  144,
        0,  154,    0,  155,  156,  157,  148,  158,  161,    0,
      148,  162,  150,  160,  163,    0,    0,  151,  166,  153,
        0,  153,  167,  152,    0,  151,  168,  150,  154,  152,
      155,  156,  157,  159,  158,  161,  155,  159,  162,  159,
      160,  163,  159,  163,  160,  166,  169,  157,  156,  167,
      170,  161,  171,  168,    0,    0,    0,    0,    0,    0,
      159,    0,    0,    0,    0,    0,  167,    0,    0,    0,
        0,    0,    0,  169,    0,    0,    0,  170,    0,  171,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,  169,  173,  173,  173,  174,  174,  174,
      175,  175,  175,  178,  178,  178,  179,    0,  179,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int rholang_mercury__flex_debug;
int rholang_mercury__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *rholang_mercury_text;
#line 1 "rholang_mercury.l"
/* -*- c -*- This FLex file was machine-generated by the BNF converter */
#define YY_NO_INPUT 1

#line 11 "rholang_mercury.l"
#define yylval rholang_mercury_lval
#define yylloc rholang_mercury_lloc
#define init_lexer rholang_mercury__init_lexer
#include "Parser.h"

static void update_loc(YYLTYPE* loc, char* text)
{
  loc->first_line = loc->last_line;
  loc->first_column = loc->last_column;
  int i = 0;
  for (; text[i] != '\0'; ++i) {
      if (text[i] == '\n') {
          ++loc->last_line;
          loc->last_column = 0;
      } else {
          ++loc->last_column;
      }
  }
}
#define YY_USER_ACTION update_loc(&yylloc, rholang_mercury_text);


#line 668 "Lexer.c"

#define INITIAL 0
#define YYINITIAL 1
#define CHAR 2
#define CHARESC 3
#define CHAREND 4
#define STRING 5
#define ESCAPED 6
#define COMMENT 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int rholang_mercury_lex_destroy (void );

int rholang_mercury_get_debug (void );

void rholang_mercury_set_debug (int debug_flag  );

YY_EXTRA_TYPE rholang_mercury_get_extra (void );

void rholang_mercury_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *rholang_mercury_get_in (void );

void rholang_mercury_set_in  (FILE * in_str  );

FILE *rholang_mercury_get_out (void );

void rholang_mercury_set_out  (FILE * out_str  );

yy_size_t rholang_mercury_get_leng (void );

char *rholang_mercury_get_text (void );

int rholang_mercury_get_lineno (void );

void rholang_mercury_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int rholang_mercury_wrap (void );
#else
extern int rholang_mercury_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( rholang_mercury_text, rholang_mercury_leng, 1, rholang_mercury_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( rholang_mercury_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( rholang_mercury_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, rholang_mercury_in))==0 && ferror(rholang_mercury_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(rholang_mercury_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int rholang_mercury_lex (void);

#define YY_DECL int rholang_mercury_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after rholang_mercury_text and rholang_mercury_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 41 "rholang_mercury.l"


#line 858 "Lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! rholang_mercury_in )
			rholang_mercury_in = stdin;

		if ( ! rholang_mercury_out )
			rholang_mercury_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			rholang_mercury_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				rholang_mercury__create_buffer(rholang_mercury_in,YY_BUF_SIZE );
		}

		rholang_mercury__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of rholang_mercury_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 173 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 420 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 43 "rholang_mercury.l"
return _SYMB_0;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 44 "rholang_mercury.l"
return _SYMB_1;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "rholang_mercury.l"
return _SYMB_2;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "rholang_mercury.l"
return _SYMB_3;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "rholang_mercury.l"
return _SYMB_4;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "rholang_mercury.l"
return _SYMB_5;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "rholang_mercury.l"
return _SYMB_6;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "rholang_mercury.l"
return _SYMB_7;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "rholang_mercury.l"
return _SYMB_8;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "rholang_mercury.l"
return _SYMB_9;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "rholang_mercury.l"
return _SYMB_10;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "rholang_mercury.l"
return _SYMB_11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "rholang_mercury.l"
return _SYMB_12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "rholang_mercury.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "rholang_mercury.l"
return _SYMB_14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "rholang_mercury.l"
return _SYMB_15;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "rholang_mercury.l"
return _SYMB_16;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "rholang_mercury.l"
return _SYMB_17;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "rholang_mercury.l"
return _SYMB_18;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "rholang_mercury.l"
return _SYMB_19;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "rholang_mercury.l"
return _SYMB_20;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "rholang_mercury.l"
return _SYMB_21;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "rholang_mercury.l"
return _SYMB_22;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "rholang_mercury.l"
return _SYMB_23;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "rholang_mercury.l"
return _SYMB_24;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "rholang_mercury.l"
return _SYMB_25;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "rholang_mercury.l"
return _SYMB_26;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "rholang_mercury.l"
return _SYMB_27;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "rholang_mercury.l"
return _SYMB_28;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "rholang_mercury.l"
return _SYMB_29;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "rholang_mercury.l"
return _SYMB_30;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "rholang_mercury.l"
return _SYMB_31;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "rholang_mercury.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "rholang_mercury.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "rholang_mercury.l"
return _SYMB_34;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "rholang_mercury.l"
return _SYMB_35;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "rholang_mercury.l"
return _SYMB_36;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "rholang_mercury.l"
return _SYMB_37;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "rholang_mercury.l"
return _SYMB_38;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "rholang_mercury.l"
return _SYMB_39;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "rholang_mercury.l"
return _SYMB_40;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "rholang_mercury.l"
return _SYMB_41;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "rholang_mercury.l"
return _SYMB_42;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "rholang_mercury.l"
return _SYMB_43;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "rholang_mercury.l"
return _SYMB_44;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "rholang_mercury.l"
return _SYMB_45;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "rholang_mercury.l"
return _SYMB_46;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "rholang_mercury.l"
return _SYMB_47;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "rholang_mercury.l"
return _SYMB_48;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "rholang_mercury.l"
return _SYMB_49;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "rholang_mercury.l"
return _SYMB_50;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "rholang_mercury.l"
return _SYMB_51;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "rholang_mercury.l"
return _SYMB_52;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "rholang_mercury.l"
return _SYMB_53;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "rholang_mercury.l"
return _SYMB_54;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "rholang_mercury.l"
return _SYMB_55;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "rholang_mercury.l"
return _SYMB_56;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "rholang_mercury.l"
return _SYMB_57;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "rholang_mercury.l"
return _SYMB_58;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "rholang_mercury.l"
return _SYMB_59;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "rholang_mercury.l"
return _SYMB_60;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "rholang_mercury.l"
return _SYMB_61;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "rholang_mercury.l"
return _SYMB_62;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "rholang_mercury.l"
/* skip */; /* BNFC: comment "//" */
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "rholang_mercury.l"
BEGIN COMMENT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "rholang_mercury.l"
BEGIN YYINITIAL;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "rholang_mercury.l"
/* skip */;
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 111 "rholang_mercury.l"
/* skip */;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 113 "rholang_mercury.l"
yylval._string = strdup(rholang_mercury_text); return _SYMB_63;
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 114 "rholang_mercury.l"
yylval._string = strdup(rholang_mercury_text); return _SYMB_64;
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 115 "rholang_mercury.l"
yylval._string = strdup(rholang_mercury_text); return _SYMB_65;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 116 "rholang_mercury.l"
yylval._string = strdup(rholang_mercury_text); return _SYMB_66;
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 117 "rholang_mercury.l"
/* ignore white space. */;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 118 "rholang_mercury.l"
return _ERROR_;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "rholang_mercury.l"
ECHO;
	YY_BREAK
#line 1320 "Lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(YYINITIAL):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed rholang_mercury_in at a new source and called
			 * rholang_mercury_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = rholang_mercury_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( rholang_mercury_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * rholang_mercury_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of rholang_mercury_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					rholang_mercury_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			rholang_mercury_restart(rholang_mercury_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) rholang_mercury_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 173 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 173 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 172);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					rholang_mercury_restart(rholang_mercury_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( rholang_mercury_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve rholang_mercury_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void rholang_mercury_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        rholang_mercury_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            rholang_mercury__create_buffer(rholang_mercury_in,YY_BUF_SIZE );
	}

	rholang_mercury__init_buffer(YY_CURRENT_BUFFER,input_file );
	rholang_mercury__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void rholang_mercury__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		rholang_mercury_pop_buffer_state();
	 *		rholang_mercury_push_buffer_state(new_buffer);
     */
	rholang_mercury_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	rholang_mercury__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (rholang_mercury_wrap()) processing, but the only time this flag
	 * is looked at is after rholang_mercury_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void rholang_mercury__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	rholang_mercury_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE rholang_mercury__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) rholang_mercury_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rholang_mercury__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) rholang_mercury_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in rholang_mercury__create_buffer()" );

	b->yy_is_our_buffer = 1;

	rholang_mercury__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with rholang_mercury__create_buffer()
 * 
 */
    void rholang_mercury__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		rholang_mercury_free((void *) b->yy_ch_buf  );

	rholang_mercury_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a rholang_mercury_restart() or at EOF.
 */
    static void rholang_mercury__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	rholang_mercury__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then rholang_mercury__init_buffer was _probably_
     * called from rholang_mercury_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void rholang_mercury__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		rholang_mercury__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void rholang_mercury_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	rholang_mercury_ensure_buffer_stack();

	/* This block is copied from rholang_mercury__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from rholang_mercury__switch_to_buffer. */
	rholang_mercury__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void rholang_mercury_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	rholang_mercury__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		rholang_mercury__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void rholang_mercury_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)rholang_mercury_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in rholang_mercury_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)rholang_mercury_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in rholang_mercury_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE rholang_mercury__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) rholang_mercury_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rholang_mercury__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	rholang_mercury__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to rholang_mercury_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       rholang_mercury__scan_bytes() instead.
 */
YY_BUFFER_STATE rholang_mercury__scan_string (yyconst char * yystr )
{
    
	return rholang_mercury__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to rholang_mercury_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE rholang_mercury__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) rholang_mercury_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in rholang_mercury__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = rholang_mercury__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in rholang_mercury__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up rholang_mercury_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		rholang_mercury_text[rholang_mercury_leng] = (yy_hold_char); \
		(yy_c_buf_p) = rholang_mercury_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		rholang_mercury_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int rholang_mercury_get_lineno  (void)
{
        
    return rholang_mercury_lineno;
}

/** Get the input stream.
 * 
 */
FILE *rholang_mercury_get_in  (void)
{
        return rholang_mercury_in;
}

/** Get the output stream.
 * 
 */
FILE *rholang_mercury_get_out  (void)
{
        return rholang_mercury_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t rholang_mercury_get_leng  (void)
{
        return rholang_mercury_leng;
}

/** Get the current token.
 * 
 */

char *rholang_mercury_get_text  (void)
{
        return rholang_mercury_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void rholang_mercury_set_lineno (int  line_number )
{
    
    rholang_mercury_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see rholang_mercury__switch_to_buffer
 */
void rholang_mercury_set_in (FILE *  in_str )
{
        rholang_mercury_in = in_str ;
}

void rholang_mercury_set_out (FILE *  out_str )
{
        rholang_mercury_out = out_str ;
}

int rholang_mercury_get_debug  (void)
{
        return rholang_mercury__flex_debug;
}

void rholang_mercury_set_debug (int  bdebug )
{
        rholang_mercury__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from rholang_mercury_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    rholang_mercury_in = stdin;
    rholang_mercury_out = stdout;
#else
    rholang_mercury_in = (FILE *) 0;
    rholang_mercury_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * rholang_mercury_lex_init()
     */
    return 0;
}

/* rholang_mercury_lex_destroy is for both reentrant and non-reentrant scanners. */
int rholang_mercury_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		rholang_mercury__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		rholang_mercury_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	rholang_mercury_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * rholang_mercury_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *rholang_mercury_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *rholang_mercury_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void rholang_mercury_free (void * ptr )
{
	free( (char *) ptr );	/* see rholang_mercury_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 120 "rholang_mercury.l"



void init_lexer(FILE *inp)
{
  rholang_mercury_restart(inp);
  yylloc.first_line   = 1;
  yylloc.first_column = 1;
  yylloc.last_line    = 1;
  yylloc.last_column  = 1;
  BEGIN YYINITIAL;
}


