[package]
name = "rho-runtime"
version = "0.1.0"
authors = ["jerry <vcer@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[build-dependencies]
bindgen = "0.57"